apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "vj-istio"
spec:
  host: "*.vj-istio.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
